### ISSUE TITLE
Why DepthwiseConv have 2 conv?

### ISSUE THREAD

**Issue by Xujianzhong** [lucidrains/conformer#2]
![image](https://user-images.githubusercontent.com/14050583/97173772-0f285200-17cc-11eb-9b22-de80d7b6f816.png)

**Comment by lucidrains** [comment]
@Xujianzhong ohh yes, you are right, I confused depth-wise conv with depth-wise separable conv!

**Comment by lucidrains** [comment]
@Xujianzhong fixed in `0.1.0`
