### ISSUE TITLE
Conformer encoder model architecture

### ISSUE THREAD

**Issue by jinglescode** [lucidrains/conformer#3]
Hi @lucidrains, here's Conformer encoder model architecture, it has a few other Modules:

![image](https://user-images.githubusercontent.com/1694368/103190773-55ee1180-490d-11eb-9c6e-d28e870d6ad5.png)

I have not started working on it, should I do a PR to include *Multi-Headed Self-Attention Module* and *Feed forward module*?

![image](https://user-images.githubusercontent.com/1694368/103190680-f98af200-490c-11eb-85c1-91521714935c.png)

![image](https://user-images.githubusercontent.com/1694368/103190710-1b847480-490d-11eb-8ea5-280749a32a24.png)

**Comment by lucidrains** [comment]
@jinglescode Hi Hong! Sure, I can add the ConformerBlock at some point. I don't think the rest of the architecture contains anything too novel

**Comment by lucidrains** [comment]
@jinglescode Are you familiar with how the SpecAug and Convolution Subsampling is done in Pytorch?

**Comment by lucidrains** [comment]
@jinglescode Hey Hong, I added the Conformer Block, let me know if that's good enough for you
